services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: road_trip_butler
      POSTGRES_PASSWORD: "LOycOeu_8avTScYBS9cgIW_7evInEM4i"
    volumes:
      - road_trip_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "8MsK5Si1uRIrgbInJlN3_GGgpytnaUDk"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: road_trip_butler_test
      POSTGRES_PASSWORD: "sC16OWhPAJ9XVyGP650fSCrch-MriTZS"
    volumes:
      - road_trip_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "IxZustXA08OpMKQauXkr1MOAwoMMnPhd"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  road_trip_butler_data:
  road_trip_butler_test_data:
